### ISSUE TITLE
/claimflag noenterplayer <player>  issue

### ISSUE THREAD

**Issue by MithrandirCraft** [akdukaan/GriefPreventionFlags#14]
**Describe the bug**
There is a malfunction with the noenterplayer flag.

**To Reproduce**
When using the command once towards a targeted player, the player is indeed blocked from entering the claim:
Eg: `/claimflag noenterplayer __Mithrandir__`

When using the command again, but inputing something else instead of a valid player name:
Eg: `/claimflag noenterplayer yyyyyy`
the command seems to recognize the word `yyyyyy`as a valid playername and unlocks the previously locked player from entring the claim.

**Expected behavior**
Invalid player names should not mess up the list of locked players (I am asuming the flag does ineed add to a list, and does not only lock one player).

**Versions:**
 - GriefPrevention version 16.18-RC1-2-g0e3a2e9
 - GPFlags version 5.11.2
 - Server version Paper 1.18.1

**Comment by drbot7** [comment]
The way that the plugin was designed, anytime you use the command, it sets the new list of blocked players to whoever is mentioned on the command without any consideration for who was previously on the list. I obviously agree that this isn't the best way to go about it. I don't even think it accounts for username changes. It definitely needs to be changed but changing it is a little more work than I'd want it to be. I'd probably have to add an extra layer of subcommands, maybe something like
- /gpflags setclaimflag noenterplayer set player1 player2 player3
- /gpflags setclaimflag noenterplayer add player4 player5
- /gpflags setclaimflag noenterplayer remove player1 player2

**Comment by akdukaan** [comment]
I know this isn't as great as what I was hoping to do about it, but I'm hoping it can be good enough for now. Just with the way I was hoping to do it, I would have to change a lot about how flags work. I might get to it in another future update if I decide it to be worth it.

The change I did make in the upcoming version makes it so that after typing /setclaimflag noenterplayer, it'll tab-complete who you have already blocked, making it much easier to just accept the tab-complete and then add another name to the list. 

I hope this helps resolve your issue!
